services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.production.local
    entrypoint: ["/bin/bash"]
    command: ["-c", "uvx --version && echo 'uvx is working!' && tail -f /dev/null"]
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "tail"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Add any additional environment variables or command arguments here
    # Example using flags (ensure env vars MCPGARDEN_PROXY_SERVER_ID is also set):
    # command: --mcpgarden-api-key your-api-key --mcpgarden-api-base-url your-base-url
